version: '3.8'

services:
  # Сервис для Kafka
  zookeeper:
    image: confluentinc/cp-zookeeper:latest
    container_name: zookeeper-1
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
      ZOOKEEPER_TICK_TIME: 2000
    deploy:
      resources:
        limits:
          memory: 1g

  kafka:
    image: bitnami/kafka:latest
    depends_on:
      - zookeeper
    ports:
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181
      KAFKA_CFG_LISTENERS: PLAINTEXT://:9092
      KAFKA_CFG_ADVERTISED_LISTENERS: PLAINTEXT://kafka:9092
      KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE: "true"

  # База данных для rating-service
  rating-db:
    image: postgres:13
    environment:
      POSTGRES_DB: rating-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5436:5432"
    volumes:
      - rating-db-data:/var/lib/postgresql/data

  # База данных для payment-service
  payment-db:
    image: postgres:13
    environment:
      POSTGRES_DB: payment-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5435:5432"
    volumes:
      - payment-db-data:/var/lib/postgresql/data

  # База данных для passenger-service
  passenger-db:
    image: postgres:13
    environment:
      POSTGRES_DB: passenger-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5434:5432"
    volumes:
      - passenger-db-data:/var/lib/postgresql/data

  # База данных для driver-service
  driver-db:
    image: postgres:13
    environment:
      POSTGRES_DB: driver-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - driver-db-data:/var/lib/postgresql/data

  # База данных для ride-service
  ride-db:
    image: postgres:13
    environment:
      POSTGRES_DB: rides-service
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    ports:
      - "5433:5432"
    volumes:
      - ride-db-data:/var/lib/postgresql/data

  # Сервис driver-service
  driver-service:
    build:
      context: ./driver-service
      dockerfile: Dockerfile
    ports:
      - "8085:8085"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://driver-db:5432/driver-service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - driver-db
      - kafka

  # Сервис passenger-service
  passenger-service:
    build:
      context: ./passenger-service
      dockerfile: Dockerfile
    ports:
      - "8081:8081"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://passenger-db:5432/passenger-service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - passenger-db
      - kafka

  # Сервис payment-service
  payment-service:
    build:
      context: ./payment-service
      dockerfile: Dockerfile
    ports:
      - "8082:8082"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://payment-db:5432/payment-service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - payment-db
      - kafka

  # Сервис rating-service
  rating-service:
    build:
      context: ./rating-service
      dockerfile: Dockerfile
    ports:
      - "8083:8083"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://rating-db:5432/rating-service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - rating-db
      - kafka

  # Сервис ride-service
  ride-service:
    build:
      context: ./rides-service
      dockerfile: Dockerfile
    ports:
      - "8084:8084"
    environment:
      SPRING_DATASOURCE_URL: jdbc:postgresql://ride-db:5432/rides-service
      SPRING_KAFKA_BOOTSTRAP_SERVERS: kafka:9092
    depends_on:
      - ride-db
      - kafka

# Тома для хранения данных PostgreSQL
volumes:
  driver-db-data:
  passenger-db-data:
  payment-db-data:
  rating-db-data:
  ride-db-data: