global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'services'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets:
          - 'passenger-service:8081'
          - 'gateway-server:8080'
          - 'driver-service:8085'
          - 'payment-service:8082'
          - 'rating-service:8083'
          - 'ride-service:8084'